server.port: 8888

#==========================================#
#============ Database settings============#
#==========================================#
ms.db.driverClassName: com.mysql.cj.jdbc.Driver
# 阿里云数据库
#ms.db.url: jdbc:mysql://120.79.95.182:3306/database_hd?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#ms.db.username: root
#ms.db.password: admin1234
# mycat 数据库
ms.db.url: jdbc:mysql://127.0.0.1:8066/TESTDB?useUnicode=true&characterEncoding=UTF-8&useSSL=false
ms.db.username: mycat
ms.db.password: 123456
# JVM 本地虚拟机
#ms.db.url: jdbc:mysql://192.168.197.128:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#ms.db.username: admin
#ms.db.password: 123456
ms.db.maxActive: 20
ms.db.maxIdle: 2
ms.db.minIdle: 2
ms.db.maxWait: 1000
ms.db.initialSize: 2
ms.db.validationQuery: SELECT 1
#ms.db.packagePath: com.hd.test.db.dao
#ms.db.configPath: classpath:com/hd/test/db/dao/**.xml

#==========================================#
#============ Mybatis settings ============#
#==========================================#
#db.mybatis.mapperLocations: classpath:com/hd/test/db/**.xml
#db.mybatis.typeAliasesPackage: com.hd.test.db
#db.mybatis.dbType: mysql
#mybatis.mapper-locations: classpath:com/hd/test/db/dao/**.xml
mybatis-plus:
  mapper-locations: classpath:com/hd/test/db/dao/**.xml
  type-aliases-package: com.hd.test.db.dao


#==========================================#
#==== redis and rabbitmq settings   =======#
#==========================================#
spring:
  redis:
    #数据库索引
    database: 10
    host: 120.79.95.182
    port: 6379
    password: cjxx_pwd_2019
    jedis:
      pool:
        #最大连接数
        max-active: 200
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 10
        #最小空闲
        min-idle: 0
    #连接超时时间
    timeout: 10000
    cache:
      clusterNodes: 120.79.95.182:6379
# DataSource Config MyBatis Plus
#  datasource:
#    driver-class-name: org.h2.Driver
#    schema: classpath:db/schema-h2.sql
#    data: classpath:db/data-h2.sql
#    url: jdbc:h2:mem:test
##    url: jdbc:mysql://120.59.97.182:3306/database_hd?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    username: root
##    password: root123
#    password: test


elastic:
  config:
    serverUris: http://120.79.95.182:9200
    username: admin
    password: es123456
